export const audioMap = {
  "John is building a treehouse ladder. He needs the rungs to be evenly spaced, and the side rails to meet the floor at a perfect corner.": "/assets/audio/audio_john_is_building_a_treehouse_l_0.mp3",
  "How can he check if his ladder is built correctly? Let's find out!": "/assets/audio/audio_how_can_he_check_if_his_ladder_1.mp3",
  "Sarah and Yuki walk past the railway station on a sunny morning.": "/assets/audio/audio_sarah_and_yuki_walk_past_the_r_2.mp3",
  "Look! The two railway tracks never touch. They stay exactly the same distance apart, forever. That is what we call parallel!": "/assets/audio/audio_look_the_two_railway_tracks_ne_3.mp3",
  "Now look at Yuki's window. The lines cross and make a perfect square corner, a right angle. That is perpendicular!": "/assets/audio/audio_now_look_at_yuki_s_window_the__4.mp3",
  "Some lines just cross at a slanted corner. Those are intersecting, but not perpendicular, because there is no right angle.": "/assets/audio/audio_some_lines_just_cross_at_a_sla_5.mp3",
  "Set the mirror to a 45-degree angle. That will make the laser bounce off at a perfect 90-degree turn and hit the gem!": "/assets/audio/audio_set_the_mirror_to_a_45_degree__6.mp3",
  "Perfect! A 45-degree mirror makes the laser reflect at a right angle and hit the gem!": "/assets/audio/audio_perfect_a_45_degree_mirror_mak_7.mp3",
  "Not quite! Set the mirror to exactly 45 degrees so the laser reflects at a perfect 90-degree angle onto the gem.": "/assets/audio/audio_not_quite_set_the_mirror_to_ex_8.mp3",
  "Adjust the new track to be PERFECTLY parallel to the existing bridge so the train can cross!": "/assets/audio/audio_adjust_the_new_track_to_be_per_9.mp3",
  "Awesome! The tracks are parallel and the train is safe!": "/assets/audio/audio_awesome_the_tracks_are_paralle_10.mp3",
  "Not quite parallel! The train will crash if the tracks aren't straight.": "/assets/audio/audio_not_quite_parallel_the_train_w_11.mp3",
  "Slice the shape PERPENDICULAR to the glowing bottom edge!": "/assets/audio/audio_slice_the_shape_perpendicular__12.mp3",
  "Ninja slice! Perfect perpendicular cut!": "/assets/audio/audio_ninja_slice_perfect_perpendicu_13.mp3",
  "Not quite! A perpendicular cut needs to be exactly straight up and down here.": "/assets/audio/audio_not_quite_a_perpendicular_cut__14.mp3",
  "Perfect! That is exactly perpendicular! You are a geometry superstar!": "/assets/audio/audio_perfect_that_is_exactly_perpen_15.mp3",
  "Not quite! Let us look at the lines again.": "/assets/audio/audio_not_quite_let_us_look_at_the_l_16.mp3",
  "Watch the tester check the corner! Does it fit exactly?": "/assets/audio/audio_watch_the_tester_check_the_cor_17.mp3",
  "What a journey today! Can you find one parallel thing and one perpendicular thing in your own room?": "/assets/audio/audio_what_a_journey_today_can_you_f_18.mp3",
  "Lesson complete! You are a Parallel and Perpendicular Lines Champion!": "/assets/audio/audio_lesson_complete_you_are_a_para_19.mp3",
  "Badge unlocked! You are a Line Explorer!": "/assets/audio/audio_badge_unlocked_you_are_a_line__20.mp3",
  "Badge unlocked! Line Builder! You completed all three stations!": "/assets/audio/audio_badge_unlocked_line_builder_yo_21.mp3",
  "Badge unlocked! Right Angle Ranger! Your tester skills are excellent!": "/assets/audio/audio_badge_unlocked_right_angle_ran_22.mp3",
  "Which pair of lines is PARALLEL?": "/assets/audio/audio_which_pair_of_lines_is_paralle_23.mp3",
  "Which pair of lines is PERPENDICULAR?": "/assets/audio/audio_which_pair_of_lines_is_perpend_24.mp3",
  "Look at these two lines. Are they parallel, perpendicular, intersecting, or neither?": "/assets/audio/audio_look_at_these_two_lines_are_th_25.mp3",
  "\"These two lines are parallel.\" True or False?": "/assets/audio/audio__these_two_lines_are_parallel__26.mp3",
  "\"These two lines are perpendicular.\" True or False?": "/assets/audio/audio__these_two_lines_are_perpendic_27.mp3",
  "A student is looking for a pair of PARALLEL lines. Which object shows this?": "/assets/audio/audio_a_student_is_looking_for_a_pai_28.mp3",
  "A builder uses a tester on the corner. Does it fit exactly?": "/assets/audio/audio_a_builder_uses_a_tester_on_the_29.mp3",
  "How many pairs of parallel lines are in this rectangle?": "/assets/audio/audio_how_many_pairs_of_parallel_lin_30.mp3",
  "How many pairs of perpendicular lines are in this shape?": "/assets/audio/audio_how_many_pairs_of_perpendicula_31.mp3",
  "Which letter has a pair of PERPENDICULAR lines?": "/assets/audio/audio_which_letter_has_a_pair_of_per_32.mp3",
  "Our friend wants to find a shape with PERPENDICULAR lines. Which one has lines that cross at a perfect 90° corner?": "/assets/audio/audio_our_friend_wants_to_find_a_sha_33.mp3",
  "Welcome to the new world! Let's go!": "/assets/audio/audio_welcome_to_the_new_world_let_s_34.mp3",
  "World complete! Great job!": "/assets/audio/audio_world_complete_great_job__35.mp3",
  "Amazing! Great streak!": "/assets/audio/audio_amazing_great_streak__36.mp3",
  "Correct! Well done!": "/assets/audio/audio_correct_well_done__37.mp3",
  "Wonderful! Now let us reflect on what you learned. Teach the mascot!": "/assets/audio/audio_wonderful_now_let_us_reflect_o_38.mp3",
  "Excellent! That is correct!": "/assets/audio/audio_excellent_that_is_correct__39.mp3",
  "Not quite, but keep trying!": "/assets/audio/audio_not_quite_but_keep_trying__40.mp3",
  "How do you feel about parallel and perpendicular lines now?": "/assets/audio/audio_how_do_you_feel_about_parallel_41.mp3",
  "You completed the challenge! Amazing work today!": "/assets/audio/audio_you_completed_the_challenge_am_42.mp3",
  "Hello! Today we are going to explore Parallel and Perpendicular Lines!": "/assets/audio/audio_hello_today_we_are_going_to_ex_43.mp3",
  "Two roads run side by side and never cross. What type of lines are they?": "/assets/audio/audio_two_roads_run_side_by_side_and_44.mp3",
  "What makes two lines 'perpendicular'?": "/assets/audio/audio_what_makes_two_lines_perpendic_45.mp3",
  "The sides of a window frame — what geometry do they show?": "/assets/audio/audio_the_sides_of_a_window_frame_wh_46.mp3"
};
